config/routes.rb
Rails.application.routes.draw do
  root 'static_pages#home'
  get '/about', to: 'static_pages#about'
  get '/access', to: 'static_pages#access'
  get '/gacha', to: 'static_pages#gacha'
  post '/gacha', to: 'static_pages#lottery'
  
  get '/signup', to: 'users#new'
  post '/signup', to: 'users#create'
  get '/login', to: 'sessions#new'
  post '/login', to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  resources :users
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/point.rb
class Point < ApplicationRecord
  belongs_to :user
  default_scope -> { order(created_at: :desc) }
  validates :user_id, presence: true
  validates :point,  numericality: {only_integer: true}
end

app/models/user.rb
# coding: utf-8
class User < ApplicationRecord
  has_many :point, dependent: :destroy
  attr_accessor :remember_token
  before_save { email.downcase! }
  validates :name, presence: true, length: { maximum: 50 }
  VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true, length: { maximum: 255 },
            format: { with: VALID_EMAIL_REGEX },
            uniqueness: { case_sensitive: false }
  has_secure_password validations: false
  validates :password, presence: true, length: { minimum: 6 }, allow_nil: true

  mount_uploader :image, ImageUploader

  #渡された文字列のハッシュ値を返す
  def User.digest(string)
    cost = ActiveModel::SecurePassword.min_cost ? BCrypt::Engine::MIN_COST :
                                                  BCrypt::Engine.cost
    BCrypt::Password.create(string, cost: cost)
  end

  #ランダムなトークンを返す
  def User.new_token
    SecureRandom.urlsafe_base64
  end

  #永続化セッションのためのユーザーをデータベースに記憶する
  def remember
    self.remember_token = User.new_token
    update_attribute(:remember_digest, User.digest(remember_token))
  end

  #渡されたトークンがダイジェストと一致したらtrueを返す
  def authenticated?(remember_token)
    return false if remember_digest.nil?
    BCrypt::Password.new(remember_digest).is_password?(remember_token)
  end

  #ユーザーログイン情報破棄
  def forget
    update_attribute(:remember_digest, nil)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
  include SessionsHelper

  def hello
    render html: "hello, world!"
  end
end

app/controllers/sessions_controller.rb
# coding: utf-8
class SessionsController < ApplicationController
    
  def new
  end

  def create
    @user = User.find_by(email: params[:session][:email].downcase)
    if @user && @user.authenticate(params[:session][:password])
      log_in(@user)
      params[:session][:remember_me] == '1' ? remember(@user) : forget(@user)
      redirect_back_or @user
    else
      flash.now[:danger] = "メールアドレス、またはパスワードが無効です。"
      render 'new'
    end
  end

  def destroy
    log_out if logged_in?
    redirect_to root_url
  end


end

app/controllers/static_pages_controller.rb
# coding: utf-8
class StaticPagesController < ApplicationController
  before_action :logged_in_user, only: [:gacha]
  
  def home
  end

  def about
  end

  def access
  end

  def gacha
  end

  def lottery
    @user = current_user
    
    if user_params[:point].to_s =~ /^[0-9]+$/
      @user.point.create!(point: user_params[:point].to_i)
      flash[:notice] = "#{user_params[:point].to_i}ポイントを取得しました。"
      redirect_to gacha_url
    else
      flash[:danger] = "整数でないです" #テスト
      redirect_to gacha_url
    end
  end

  private
   def user_params
     params.permit(:point)
   end

   #beforeアクション

   #ログイン済みユーザーかどうか
   def logged_in_user
     unless logged_in?
       store_location
       flash[:danger] = ""
       redirect_to login_url
     end
   end

end

app/controllers/users_controller.rb
# coding: utf-8
class UsersController < ApplicationController
  before_action :logged_in_user, only: [:edit, :update, :destroy]
  before_action :correct_user,   only: [:edit, :update]
  
  def show
    @user = User.find(params[:id])
  end
  
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      @user.point.create!(point: 10)
      log_in @user
      flash[:success] = "登録ありがとうございます。"
      redirect_to @user
    else
      render 'new'
    end
  end
  
  def edit
    @user = User.find(params[:id])
  end

  def update
    @user = User.find(params[:id])
    if @user.update_attributes(user_params)
      flash[:success] = "プロフィール編集完了いたしました。"
      redirect_to @user
    else
      render 'edit'
    end
  end

  private
   def user_params
     params.require(:user).permit(:name, :email, :password, :password_confirmation, :image)
   end

   #beforeアクション

   #ログイン済みユーザーかどうか
   def logged_in_user
     unless logged_in?
       store_location
       flash[:danger] = ""
       redirect_to login_url
     end
   end

   def correct_user
     @user = User.find(params[:id])
     redirect_to(root_url) unless current_user == @user
   end

end

app/helpers/application_helper.rb
module ApplicationHelper
  def full_title(page_title = '')
    base_title = 'shop'
    if page_title.empty?
      base_title
    else
      page_title+ " | " + base_title
    end
  end
end

app/helpers/sessions_helper.rb
# coding: utf-8
module SessionsHelper

  #渡されたユーザーでログインする
  def log_in(user)
    session[:user_id] = user.id
  end

  #ユーザーのセッションを永続化
  def remember(user)
    user.remember
    cookies.permanent.signed[:user_id] = user.id
    cookies.permanent[:remember_token] = user.remember_token
  end

  #現在ログインしているユーザーを返す
  def current_user
    if (user_id = session[:user_id])
      @current_user ||= User.find_by(id: user_id)
    elsif (user_id = cookies.signed[:user_id])
      user = User.find_by(id: user_id)
      if user && user.authenticated?(cookies[:remember_token])
        log_in(user)
        @current_user = user
      end
    end
  end
 
  #ログインしていればtrue
  def logged_in?
    !current_user.nil?
  end

  #永続セションの破棄
  def forget(user)
    user.forget
    cookies.delete(:user_id)
    cookies.delete(:remember_token)
  end

  #現在のユーザーをログアウトする
  def log_out
    forget(current_user)
    session.delete(:user_id)
    @current_user = nil
  end

  #記憶したURLにリダイレクト
  def redirect_back_or(default)
    redirect_to(session[:forwarding_url] || default)
    session.delete(:forwarding_url)
  end

  #アクセスしようとしたURLを覚えておく
  def store_location
    session[:forwarding_url] = request.original_url if request.get?
  end
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/_footer.html.erb
<footer class="footer">
  <nav>
    <ul>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "About", '#' %></li>
      <li><%= link_to "About", '#' %></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-default">
  <div class="container">
    <%= link_to "あaaaaaaaa", root_path, id: "logo" %>
    <nav>

      <ul class="nav navbar-nav navbar-right">
	<li><%= link_to "アバウト", about_path %></li>
	<li><%= link_to "アクセス", access_path %></li>
	<li><%= link_to "メニュー＆食券", "#" %></li>
	<li><%= link_to "状況", "#" %></li>
	<li><%= link_to "マップ", "#" %></li>
	<% if logged_in? %>
	　<li><%= link_to "ガチ", gacha_path %></li>
	  <li><%= link_to "全アカウント", users_path %></li>
	  <li class="dropdown">
	    <a href="#" class="dropdown-toggle" data-toggle="dropdown">
	      Account</a>
	    <ul class="dropdown-menu">
	      <li><%= link_to "アカウント", current_user %></li>
	      <li><%= link_to "ユーザー設定", edit_user_path(current_user) %></li>
	      <li class="divider"></li>
	      <li>
		<%= link_to "ログアウト", logout_path, method: :delete %>
	      </li>
	    </ul>
	  </li>
	<% else %>
	  <li><%= link_to "新規登録", signup_path %></li>
	  <li><%= link_to "ログイン", login_path %></li>
	<% end %>	
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_rails_default.html.erb
<%= csrf_meta_tags %>

<%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
<%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= render 'layouts/rails_default' %>
    <%= render 'layouts/shim' %>
  </head>


  <body>
    <%= render 'layouts/header' %>
    <div class="container-fluid">
      <% flash.each do |message_type, message| %>
        <%= content_tag(:div, message, class: "alert alert-#{message_type}") %>
      <% end %>
      <%= yield %>
      <%= render 'layouts/footer' %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @user.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      <%= @user.errors.count %>つのエラーがあります。
    </div>
    <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>  

app/views/static_pages/about.html.erb
<% provide(:title, "ABOUT") %>
<h1>About</h1>
<p>this web site is ramen.</p>

app/views/static_pages/access.html.erb
<% provide(:title, "ACCESS") %>
<h1>Access</h1>
<p>住所</p>
<div>map</div>
<%= map(:center => {
  :latlng => [36, 140],
  :zoom => 18
}) %>

app/views/static_pages/gacha.html.erb
<% provide(:title, "Gacha") %>
<h1>gacha</h1>

<div>
  <%= button_to("ガチャ", gacha_path, method: :post, params: {point: 200})   %>
</div>

app/views/static_pages/home.html.erb
<% provide(:title, "HOME") %>
<h1>タイトル</h1>

<div class="home-main-container">
  <h1>ラーメン</h1>
</div>

<div class="left"> 
  <h2>新規登録者</h2>
  <%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>
</div>
<span class="glyphicon glyphicon-time" aria-hidden="true"></span>

app/views/users/edit.html.erb
<% provide(:title, "Edit") %>
<h1>プロフィール編集</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <div class="form-group">
      <%= form_for @user, html: { multipart: true } do |f| %>
        <%= render 'shared/error_messages' %>
	
	<%= f.label :name, "アカウント名" %>
	<%= f.text_field :name, class: 'form-control' %>

	<%= f.label :email, "メールアドレス" %>
	<%= f.text_field :email, class: 'form-control' %>

	<%= f.label :password, "パスワード" %>
	<%= f.password_field :password, class: 'form-control' %>

	<%= f.label :password_confirmaiton, "パスワード再入力" %>
	<%= f.password_field :password_confirmation, class: 'form-control' %>

	<%= f.label :image, "プロフィール写真" %>
	<%= f.file_field :image, class: "dropzone fallback form-control form-control-file" %>
      
	<%= f.submit "編集を保存", class: "btn btn-primary" %>
      <% end %>


    </div>
  </div>
</div>

app/views/users/index.html.erb
<%= provide(:title, '全アカウント') %>
<h1>全アカウント</h1>

<ul class="users">
  <% @users.each do |user| %>
    <li>
      <%= image_tag(user.image, width: 50, height: 50) %>
      <%= link_to user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/new.html.erb
<% provide(:title, "Sign up")%>
<h1>新規登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_for(@user, url: signup_path) do |f| %>
      <%= render 'shared/error_messages' %>
    
      <%= f.label :name, "アカウント名" %>
      <%= f.text_field :name, class: 'form-control' %>

      <%= f.label :email, "メールアドレス" %>
      <%= f.text_field :email, class: 'form-control' %>

      <%= f.label :password, "パスワード" %>
      <%= f.password_field :password, class: 'form-control' %>

      <%= f.label :password_confirmation, "パスワードを表示する" %>
      <%= f.password_field :password_confirmation, class: 'form-control' %>

      <%= f.submit "アカウント作成", class: "btn btn-primary" %>
    <% end %>
  </div>
</div>

app/views/users/show.html.erb
<% provide(:title, @user.name) %>
<h1>
  <%= @user.name %>
</h1>
<div class="image-center">
<% if @user.image? %>
  <%= image_tag @user.image.url  %>
<% else %>
  <%= image_tag 'nothing.jpg' %>
<% end %>
</div>

<div>ポイント</div>
<% if @user.point %>
<% sum = 0 %>
  <% @user.point.each do |point| %>
     <% sum += point.point %>
  <% end %>
<h2><%= sum %></h2>
<% else %>
  <h1>no point</h1>
<% end %>